name: Create artefact for PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: ''
      - name: Prepare environment
        run: |
          mkdir -p ./out
      - name: Run pdflatex prebiber on main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -output-directory=./out -shell-escape
      - name: Run biber
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.bcf
          compiler: biber
          args: --input-directory=./out --output-directory=./out
      - name: Run pdflatex on main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -output-directory=./out main.tex -shell-escape
      - name: Upload pdf to workflow final
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Final_built
          path: out
